src/Entity/Demande.php
<?php

namespace App\Entity;

use App\Repository\DemandeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DemandeRepository::class)
 */
class Demande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Zone::class)
     */
    private $entrepotSource;

    /**
     * @ORM\ManyToOne(targetEntity=Zone::class)
     */
    private $entrepotDest;

    /**
     * @ORM\ManyToOne(targetEntity=Article::class)
     */
    private $article;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite;

    /**
     * @ORM\ManyToOne(targetEntity=Unite::class)
     */
    private $unite;

    /**
     * @ORM\Column(type="date")
     */
    private $dateCreation;

    /**
     * @ORM\Column(type="date")
     */
    private $dateBesoin;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class)
     */
    private $idDemandeur;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class)
     */
    private $idCariste;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Etat;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateValidation;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEntrepotSource(): ?Zone
    {
        return $this->entrepotSource;
    }

    public function setEntrepotSource(?Zone $entrepotSource): self
    {
        $this->entrepotSource = $entrepotSource;

        return $this;
    }

    public function getEntrepotDest(): ?Zone
    {
        return $this->entrepotDest;
    }

    public function setEntrepotDest(?Zone $entrepotDest): self
    {
        $this->entrepotDest = $entrepotDest;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getUnite(): ?Unite
    {
        return $this->unite;
    }

    public function setUnite(?Unite $unite): self
    {
        $this->unite = $unite;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getDateBesoin(): ?\DateTimeInterface
    {
        return $this->dateBesoin;
    }

    public function setDateBesoin(\DateTimeInterface $dateBesoin): self
    {
        $this->dateBesoin = $dateBesoin;

        return $this;
    }

    public function getIdDemandeur(): ?Utilisateur
    {
        return $this->idDemandeur;
    }

    public function setIdDemandeur(?Utilisateur $idDemandeur): self
    {
        $this->idDemandeur = $idDemandeur;

        return $this;
    }

    public function getIdCariste(): ?Utilisateur
    {
        return $this->idCariste;
    }

    public function setIdCariste(?Utilisateur $idCariste): self
    {
        $this->idCariste = $idCariste;

        return $this;
    }

    public function getEtat(): ?bool
    {
        return $this->Etat;
    }

    public function setEtat(bool $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }

    public function getDateValidation(): ?\DateTimeInterface
    {
        return $this->dateValidation;
    }

    public function setDateValidation(?\DateTimeInterface $dateValidation): self
    {
        $this->dateValidation = $dateValidation;

        return $this;
    }
}

src/Controller/DemandeurController.php
<?php

namespace App\Controller;

use App\Entity\Demande;
use App\Entity\Article;
use App\Entity\Unite;
use App\Entity\Zone;
use App\Entity\Utilisateur;
use App\Entity\Profile;
use App\Form\CreationDemandeType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Knp\Component\Pager\PaginatorInterface;

/**
 * Require ROLE_DEMANDEUR for *every* controller method in this class.
 *
 * @IsGranted("ROLE_DEMANDEUR")
 */
class DemandeurController extends AbstractController
{
    /**
     * Require ROLE_DEMANDEUR for only this controller method.
     * 
     * @IsGranted("ROLE_DEMANDEUR")
     * 
     * @Route("/dem", name="demandeur")
     */  
    public function demDashboard(): Response
    {
        $this->denyAccessUnlessGranted('ROLE_DEMANDEUR', null, 'User tried to access a page without having ROLE_DEMANDEUR');
        return $this->render('demandeur/demandeurPage.html.twig', [
            'controller_name' => 'DemandeurController',
        ]);
    }

    /**
     * Controlleur pour la liste des demandes du demandeur
     *
     * Require ROLE_DEMANDEUR for only this controller method.
     * 
     * @IsGranted("ROLE_DEMANDEUR")
     * 
     * @Route("/dem/afficheListeDemandeDemandeur", name="afficheListeDemandeDemandeur")
     */  
    public function afficheListeDemandeDemandeur(Request $request, PaginatorInterface $paginator):Response
    {
        $repository= $this->getDoctrine()->getRepository(Demande::class);
        $user = $this->get('security.token_storage')->getToken()->getUser();
        $donnees = $repository->findAllDemandesDemandeur($user->getid());

        if (!$donnees) {
            $this->addFlash('pb', "pas de demande");
        }

        $listeDemande = $paginator->paginate(
            $donnees, // Requête contenant les données à paginer (ici nos demandes)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            7, // Nombre de résultats par page
        );

        return $this->render('demandeur/afficheListeDemande.html.twig', array(
                'listeDemande' => $listeDemande,
                'nbPages' => ceil($listeDemande->getTotalItemCount()/7))
        );
    }

    /**
     * Controlleur de création de demandes
     *
     * Require ROLE_DEMANDEUR for only this controller method.
     * 
     * @IsGranted("ROLE_DEMANDEUR")
     * 
     * @Route("/dem/formulaireCreationDemande", name="formulaireCreationDemande")
     */
    public function formulaireCreationDemande(Request $request): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $repositoryU=  $entityManager->getRepository(Unite::class);
        $listeUnite = $repositoryU->findAllUnite();
        if (!$listeUnite) {
            throw $this->createNotFoundException(
                'pas d\'unite'
            );
        }
        $repositoryA=  $entityManager->getRepository(Article::class);
        $listeArticle = $repositoryA->findAllArticle();
        if (!$listeArticle) {
            throw $this->createNotFoundException(
                'pas d\'article'
            );
        }
        $repositoryE=  $entityManager->getRepository(Zone::class);
        $listeEntrepotS = $repositoryE->findAllEntrepot();
        $listeEntrepotD = $repositoryE->findAllEntrepot();
        if (!$listeEntrepotD) {
            throw $this->createNotFoundException(
                'pas d\'entrepot'
            );
        }
        $dateDemain = new \DateTime();
        $dateDemain->add(new \DateInterval('P1D'));
        $dateDemain = date_format($dateDemain, 'Y-m-d');

        return $this->render('demandeur/AjouterDemande.html.twig', [
            'listeUnite' => $listeUnite,
            'listeArticle' => $listeArticle,
            'listeEntrepotS' => $listeEntrepotS,
            'listeEntrepotD' => $listeEntrepotD,
            'dateDemain' => $dateDemain
        ]);
    }

    /**
     * Controlleur d'ajout de demandes
     *
     * Require ROLE_DEMANDEUR for only this controller method.
     * 
     * @IsGranted("ROLE_DEMANDEUR")
     * 
     * @Route("/dem/AjouterDemande", name="AjouterDemande")
     */  
    public function AjouterDemande(Request $request):Response
    {
        $entityManager = $this->getDoctrine()->getManager();

        $demande = new Demande();

        if ($request->isMethod('POST')) {
            if ($this->verificationCreationDemande(
                $request->request->get("form")['dateBesoin'],
                $request->request->get("form")['entrepotS'],
                $request->request->get("form")['entrepotD'],
                $request->request->get("form")['article'],
                $request->request->get("form")['quantite'],
                $request->request->get("form")['unite']
            )) {
                $user = $this->get('security.token_storage')->getToken()->getUser();
                $demande->setIdDemandeur($user);
                $demande->setEtat(0);
                $demande->setDateCreation(new \DateTime());
                $dateBesoin = $request->request->get("form")['dateBesoin'];
                $demande->setDateBesoin(new \DateTime($dateBesoin));
                $entrepotS = $entityManager->getRepository(Zone::class)->find($request->request->get("form")['entrepotS']);
                $demande->setEntrepotSource($entrepotS);
                $entrepotD = $entityManager->getRepository(Zone::class)->find($request->request->get("form")['entrepotD']);
                $demande->setEntrepotDest($entrepotD);
                $article =  $entityManager->getRepository(Article::class)->find($request->request->get("form")['article']);
                $demande->setArticle($article);
                $quantite = $request->request->get("form")['quantite'];
                $demande->setQuantite($quantite);
                $unite =  $entityManager->getRepository(Unite::class)->find($request->request->get("form")['unite']);
                $demande->setUnite($unite);
                $entityManager->persist($demande);
                $entityManager->flush();
                $this->addFlash('success', 'la demande a bien été créée');
                return $this->redirect($this->generateUrl("afficheListeDemandeDemandeur"));
            }
        }
        return $this->redirect($this->generateUrl("formulaireCreationDemande"));
    }

    /**
     * Controlleur de vérification de création de demandes
     *
     * Require ROLE_DEMANDEUR for only this controller method.
     * 
     * @IsGranted("ROLE_DEMANDEUR")
     */  
    public function verificationCreationDemande(String $dateBesoin, String $idES, String $idED, String $idArticle, String $quantite, String $idUnite): bool
    {
        $estValide = true;
        if ($dateBesoin == "" or $idES == "" or $idED == "" or $idArticle == "" or $quantite == "" or $idUnite == "") {
            $this->addFlash('erreur', "champ vide");
            $estValide = false;
        }
        $repositoryU= $this->getDoctrine()->getRepository(Unite::class);
        $profile = $repositoryU->find($idUnite);

        if (!$profile) {
            $this->addFlash('erreur', "l'unité selectionné n'existe pas");
            $estValide = false;
        }

        $repositoryE= $this->getDoctrine()->getRepository(Zone::class);
        $EntrepotD = $repositoryE->find($idED);
        $EntrepotS = $repositoryE->find($idES);

        if (!$EntrepotS or !$EntrepotD) {
            $this->addFlash('erreur', "l'entrepot selectionné n'existe pas");
            $estValide = false;
        }

        $repositoryA= $this->getDoctrine()->getRepository(Article::class);
        $article = $repositoryA->find($idArticle);

        if (!$article) {
            $this->addFlash('erreur', "l'article selectionné n'existe pas");
            $estValide = false;
        }
        $ajd = new \DateTime();
        if ($ajd >= (new \DateTime($dateBesoin))) {
            $this->addFlash('erreur', "la date selectionné est antérieur à aujourd'hui");
            $estValide = false;
        }
        if ($quantite<=0) {
            $this->addFlash('erreur', "la quantité selectionnée est inférieur ou égale à 0");
            $estValide = false;
        }
        if ($idED == $idES) {
            $this->addFlash('erreur', "l'entrepot source est le même que l'entrepot destination");
            $estValide = false;
        }
        return $estValide;
    }

    /**
     * Controlleur d'affichage du profile du demandeur
     *
     * Require ROLE_DEMANDEUR for only this controller method.
     * 
     * @IsGranted("ROLE_DEMANDEUR")
     * 
     * @Route("/dem/afficheProfileDemandeur", name="afficheProfileDemandeur")
     */  
    public function afficheProfileDemandeur(): Response
    {
        $user = $this->getUser();
        return $this->render('demandeur/afficheProfile.html.twig', ['utilisateur'=> $user]);
    }

    /**
     * Controlleur de modification du profile du demandeur
     *
     * Require ROLE_DEMANDEUR for only this controller method.
     * 
     * @IsGranted("ROLE_DEMANDEUR")
     * 
     * @Route("/dem/modificationProfileDemandeur", name="modificationProfileDemandeur")
     */  
    public function modificationProfileDemandeur(Request $request): Response
    {   
        $utilisateur = $this->getUser();
        $idUtilisateur = $utilisateur->getId();
        $entityManager = $this->getDoctrine()->getManager();
        $repositoryU=  $entityManager->getRepository(Utilisateur::class);
        $utilisateur = $repositoryU->find($idUtilisateur);

        if (!$utilisateur) {
            throw $this->createNotFoundException(
                'pas d\'utilisateur pour l\' id : '.$id

templates/demandeur/afficheListeDemande.html.twig
{% extends 'base.html.twig'%}
{% block body %}
<div class="table-responsive">
        <table class="table table-striped mt-5 ">
        <thead class="table-light">
            <tr>    
                <th scope="col">Etat</th>
                <th scope="col" class="middle">Date Validation</th>
                <th scope="col">Date Creation</th>
                <th scope="col">Date Besoin</th>
                <th scope="col">Entrepot Source</th>
                <th scope="col">Entrepot Destinataire</th>
            	<th scope="col">Article</th>
            	<th scope="col">Qte req</th>
            	<th scope="col">Unité</th>
                <th scope="col">Cariste</th>
            </tr>
        </thead>
        <tbody>
        {% for demande in listeDemande %}
            <tr>
                {% if demande.etat == 0 %}
                    <td>❌</td>
                {% else %}
                    <td>✅</td>
                {% endif %}
                {% if demande.date_valide %}
                    <td>{{ demande.date_valide|date('d-m-Y') }}</td>
                {% else %}
                    <td>{{ demande.date_valide }}</td>
                {% endif %}
                <td>{{ demande.date_creation|date('d-m-Y') }}</td>
                <td>{{ demande.date_besoin|date('d-m-Y') }}</td>
                <td>{{ demande.entrepot_source_libelle }}</td>
            	<td>{{ demande.entrepot_dest_libelle }}</td>
                <td>{{ demande.article_libelle }}</td>
                <td>{{ demande.quantite}}</td>
                <td>{{ demande.unite_libelle  }}</td>
                {% if demande.nom_cariste %}
                    <td>{{ demande.nom_cariste  }}</td>
                {% else %}
                    <td>En cours d'attribution</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
        </table>
        <div><a class="btn-outline-primary btn mx-5 fw-bold" href="{{ path('formulaireCreationDemande') }}">Faire une nouvelle Demande</a></div>
        <div>
            {% include 'pagination.html.twig' with {'pagination': listeDemande} %}
        </div> 
</div>
{% endblock %}

templates/demandeur/afficheProfile.html.twig
{% extends 'base.html.twig'%}
{% block body %}
<div class="table-responsive profile">
<table class="table mx-auto">
  <thead>
    <tr>
      <th scope="col">Information</th>
      <th scope="col">Utilisateur</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Login</th>
      <td>{{utilisateur.login}}</td>
    </tr>
    <tr>
      <th scope="row">Nom</th>
      <td>{{utilisateur.nom}}</td>
    </tr>
    <tr>
      <th scope="row">Prénom</th>
      <td>{{utilisateur.prenom}}</td>
    </tr>
    <tr>
      <th scope="row">E-mail</th>
      <td>{{utilisateur.email}}</td>
    </tr>
  </tbody>
</table>
</div>
<div class="d-grid gap-2 d-md-flex justify-content-md-end mx-5">
  <a class="btn btn-primary " href="{{ path('modificationProfileDemandeur') }}">mettre à jour le profile</a>
  <a class="btn btn-primary" href="{{ path('modificationPasswordDemandeur') }}">modifier le mot de passe</a>
</div>
{% endblock %}

templates/demandeur/ajouterDemande.html.twig
{% extends 'base.html.twig'%}
{% block body %}
<form method="post" action="{{ path('AjouterDemande') }}">
	<div class="form-group d-flex justify-content-center mt-5">
   	<fieldset>
   		<legend>Creation d'une nouvelle demande</legend>
		<div>
		    <label for="form_dateBesoin">Date du Besoin</label>
		    <input class="form-control" type="date" id="form_dateBesoin" name="form[dateBesoin]" value="{{dateDemain}}" />
		</div>
		<div>
		    <label for="form_entrepotSource">Entrepot Source</label>
		    <select class="custom-select form-control" name="form[entrepotS]" id="form_entrepotSource" required>
				<option value="">-- Selectionner un Entrepot Source --</option>
			{% for EntrepotS in listeEntrepotS %}
	         	<option value={{EntrepotS.id}}>{{EntrepotS.libelle_entrepot}}</option>
	        {% endfor %}
	    	</select>
		</div>
		<div>
		    <label for="form_entrepotDest">Entrepot Destination</label>
		    <select class="custom-select form-control" name="form[entrepotD]" id="form_entrepotDest" required>
		    	<option value="">-- Selectionner un Entrepot Destinataire --</option>
			{% for EntrepotD in listeEntrepotD %}
	         	<option value={{EntrepotD.id}}>{{EntrepotD.libelle_entrepot}}</option>
				}
	        {% endfor %}
	    	</select>
		</div>
		<div>
		    <label for="form_article">Article</label>
		    <select class="custom-select form-control" name="form[article]" id="form_article" required>
		    	<option value="">-- Selectionner un Article --</option>
			{% for Article in listeArticle %}
	         	<option value={{Article.id}}>{{Article.libelle_article}}</option>
	        {% endfor %}
	    	</select>
		</div>
		<div>
		    <label for="form_quantite">Quantité</label>
		    <input class="form-control" type="number" id="form_quantite" name="form[quantite]" value="" placeholder="-- Saisir une Quantité --" />
		</div>
		<div>
		    <label for="form_unite">Unite</label>
		    <select class="custom-select form-control" id="form_unite" name="form[unite]" required>
		    	<option value="">-- Selectionner une Unité --</option>
			{% for Unite in listeUnite %}
	         	<option value={{Unite.id}}>{{Unite.libelle_unite}}</option>
	        {% endfor %}
	    	</select>
		</div>
		<div>
		    <label for="form_save"></label>
		    <input class="btn btn-primary d-flex justify-content-center" type="submit" id="form_save" name="form[save]" />
		</div>
	</fieldset>
	</div>
</form>	
{% endblock %}

templates/demandeur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AdminController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/tdasilva/Documents/projet/SAP/src/Controller/AdminController.php'|file_link(0) }}">src/Controller/AdminController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/tdasilva/Documents/projet/SAP/templates/admin/index.html.twig'|file_link(0) }}">templates/admin/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/demandeur/modificationPassword.html.twig
{% extends 'base.html.twig'%}
{% block body %}
<form method="post" action="{{ path('modificationPasswordDemandeur') }}">
	<div class="form-group d-flex justify-content-center mt-5">
   	<fieldset>
   		<legend>modification du mot de passe de : </legend>
   		<legend class="d-flex justify-content-center">{{utilisateur.nom}} {{utilisateur.prenom}} </legend>
		<div>
		    <label for="form_oldmotdepasse">Ancien Mot de Passe</label>
		    <input class="form-control" type="password" maxlenght ="255" id="form_oldmotdepasse" name="form[oldmotdepasse]"  required/>
		</div>
		<div>
		    <label for="form_motdepasse">Nouveau Mot de Passe</label>
		    <input class="form-control" type="password" maxlenght ="255" id="form_motdepasse" name="form[motdepasse]"  required/>
		</div>
		<div>
		    <label for="form_save"></label>
		    <input class="btn btn-primary d-flex justify-content-center" type="submit" id="form_save" name="form[save]" />
		</div>
	</fieldset>
	</div>
</form>	
{% endblock %}

templates/demandeur/modificationProfile.html.twig
{% extends 'base.html.twig'%}
{% block body %}
<form method="post" action="{{ path('modificationProfileDemandeur') }}">
	<div class="form-group d-flex justify-content-center mt-5">
   	<fieldset>
   		<legend>modification du demandeur : {{utilisateur.id}} </legend>
		<div>
		    <label for="form_login">Login</label>
		    <input class="form-control" type="text" maxlenght ="50" id="form_login" name="form[login]" value="{{utilisateur.login}}" required />
		</div>
		<div>
		    <label for="form_nom">Nom</label>
		    <input class="form-control" type="text" maxlenght ="255" id="form_nom" name="form[nom]" value="{{utilisateur.nom}}" required />
		</div>
		<div>
		    <label for="form_prenom">Prénom</label>
		    <input class="form-control" type="text" maxlenght ="255" id="form_prenom" name="form[prenom]" value="{{utilisateur.prenom}}" required/>
		</div>
		<div>
		    <label for="form_mail">E-mail</label>
		    <input class="form-control" type="mail" maxlenght ="255" id="form_mail" name="form[mail]" value="{{utilisateur.email}}" required/>
		</div>
		<div>
		    <label for="form_save"></label>
		    <input class="btn btn-primary d-flex justify-content-center" type="submit" id="form_save" name="form[save]" />
		</div>
	</fieldset>
	</div>
</form>	
{% endblock %}